### ISSUE TITLE
Percentual value of the subcourse grades in the master course does not match the value in the original course

### ISSUE THREAD

**Issue by jjliaw** [mudrd8mz/moodle-mod_subcourse#29] opened 2018-12-03 01:38 UTC
Hi David:

Thank you for this FANTASTIC plugin--this allows teachers to build robust learning modules and then use a master "dashboard" course to tie together the subcourses!

Wanted to a report a bug if any teachers use Natural Aggregation for grades (which is when a grade is simply the total of points earned divided by points possible)--the subcourse plugin does a great job of reporting back the points earned, EXCEPT if a teacher does a grade override to Exclude a grade for a student. 

The actual subcourse calculates the grade correctly, but when it passes the grade to the "dashboard" course, the Subcourse plugin still pulls the Total Points possible without factoring in the lower grade total for any students with a teacher override to Exclude any grades for a student.

If you need screenshots I can upload them somewhere and share them.

Thank you for sharing this great plugin with the Moodle community!

**Comment by mudrd8mz** [comment] 2018-12-03 09:36
Hi Joseph, and thanks for nice words about the plugin. I'll try to reproduce the steps you describe and will let you know.

**Comment by mudrd8mz** [comment] 2019-01-15 17:37
Sorry, still did not get to this but it is on my radar. Meanwhile, step by step instructions to reproduce the problem (and what is the expected behaviour) will help. Thanks in advance!

**Comment by jjliaw** [comment] 2019-02-03 23:14
Hi David:

Thanks for your work on Subcourse--saw that you had a new release recently--thank you!

Here's how to reproduce the bug for calculating grades with Natural Aggregation:

1.  Setup a Test Subcourse and set the grading method to Natural Aggregation (a common method used by teachers where the grade is calculated by simply taking the total points earned divided by total points possible).

2.  Create a few assignments, and manually enter in some grades for test students, but do a grade override for a Test Student and Exclude an assignment.  Note that within the subcourse, Moodle calculates the grade correctly using Natural Aggregation (for example, let's say you have 4 assignments each worth 25 points, and you exclude one of the assignments for a student due to illness, extenuating circumstances, etc.  Now that student's grade will only be calculated out of 75 points.)

3.  In the "Master course", add in the Test Subcourse.  Note that in the grade book, all of the students grades will be calculated accurately, except for the Test Student with the Excluded assignment--the Test Student should have their grade only calculated out of 75 points, but the Subcourse module will pass on the grade to be out of 100 points.

Thanks for looking into this and for sharing your great work with the Moodle community!

**Comment by mudrd8mz** [comment] 2019-07-08 20:38
Hi Joseph.

I was able to replicate locally what you describe. The thing is that when calculating the percentage grade in the original subcourse, the excluded grade item is not counted into the sum of the maximum grade. So as you correctly state in your example, while all students' percentage grades will be calculated as out of 100, this one particular student's grade will be counted as out of 75 points.

But in the master course, the grade item representing the subcourse can only have one maximum grade common for all students. There is no way in moodle to say that this grade item's max grade is 100 for all the students but 75 for this exceptional one. So the percentual grade will be calculated as out of 100 points for all the students. And while the actual number of points (the "real" value grade) will match in both places, the "percentual" grade will not match for this one student.

The very same behaviour can been when using the "Exclude empty grades" aggregation option.

### Steps to reproduce ###

To further illustrate the issue even more, I've amended the reported steps to reproduce as follows:

1. In the subcourse, create three grade items with 0-10 points each.
2. Set the display of the course root category item's aggregation method to "Natural", enable the "Exclude empty grades" checkbox and set the grade display type to "Real (percentage)".
3. Give students grades and (a) explicitly exclude some item and (b) leave some grade empty without any value.
4. Observe how the percentual grades are calculated for students who have some grades excluded.
5. Set up the subcourse module instance and in the master course gradebook, set the subcourse grade item's display type to "Real (percentage)"
6. Compare the point values and percentages in the original subcourse and in the master course.

We cannot achieve that both value and percentage matches - as the grade item cannot have different max grade valuefor different users. At the moment, the real value will match in both places (as that is the one transferred from the subcourse to the master), but percentages will be different. I have a patch that makes it so that the percentage value will match in both places, but the real value will be different (so it appears as if the student had more points).

The only solution coming to my mind is to have this configurable so that the teacher can specify whether it is desired to keep the real value synced, or the percentage value synced.

**Comment by jjliaw** [comment] 2019-07-09 19:48
Hi David:

Wow--thanks for your extremely detailed responses and thorough testing and explanation of the "bug" and limitations of the Moodle gradebook with the Subcourse Module.

Actually, I think you're patch that makes the percentage matches in both places will work (in other words, if a student had 4 assignments out of 25 points with a total of 100 points for the course, but then due to illness / extenuating circumstances, etc. would be excluded from 1 assignment, so then the Subcourse Natural Aggregation method would calculate the grade only out of 75 points, and then when the natural aggregation grade is passed on to the Master Course it would be correctly calculated for the student out of only 75 points vs. 100 points for everyone else!).

If you want me to test out your patch with my courses, I would be happy to since this is the summer term and I don't have any active courses now and can do some poking around with fictitious student accounts.

Thanks again for sharing this great tool with the Moodle Community and empowering teachers to build robust courses and content for their students!

Regards,

--Joe

**Comment by jjliaw** [comment] 2020-04-13 13:38
Hi David:

Hope you and your family are doing well amidst the COVID-19 crisis.

Just wanted to check if by any chance you have the patched code available that would allow instructors to exempt students in a subcourse from an assignment, and then have it populate the exempted "percentage" into the master course and calculate final grade correctly due to the exemption for that single student.

Now more than ever, ed-tech tools like Moodle are critical in delivering remote learning to our students, and given that some of our students are placed in precarious circumstances due to the crisis (e.g. being displaced from their homes, or having to move in with another parent or family member and having limited access to wifi), being able to give instructors the discretion to exempt students from assignments using the fantastic Subcourse module would be extremely helpful!

If you want me to test out the code on my server first and then report back to you, I would be happy to do that!  Currently we are still running Moodle 3.5 before upgrading this summer.

Thank you for any assistance you can offer, and for sharing your fantastic work with the Moodle community!

Regards,

--Joe

**Comment by mudrd8mz** [comment] 2020-07-11 15:52
![image](https://user-images.githubusercontent.com/85831/87227956-5fef7880-c39e-11ea-9e73-6a1b4cbe9687.png)

This is an example of grades in a referenced course to illustrate the problem. Note that because some of the grades are excluded (either because they have been explicitly marked to be excluded, or because they are empty), then the real value (such as 5.00, 10.00 or 20.00 out of 20 points) does not always lead to the same percentual value (100.00%, 66.67%, 50.00% etc).

The issue here is: when fetching this final grade into the subcourse activity, should we make it so that the real value matches in both places, or should the percentage match in both places.

To address this, a new setting is being add to the Subcourse module setting form so that the teacher can control the expected behaviour depending on how they use gradebook.

**Comment by jjliaw** [comment] 2020-07-11 16:51
Hi David:

Thank you for taking time out of your busy schedule to address this issue, especially before a new school year starts!  

Your new setting will help teachers use the subcourse module effectively--I propose that the "default" setting of the subcourse module for excluded grades be that the "real" points are fetched into the master course since this is what most teachers would expect.  

So in your screenshot, the student Batur would have received 20 out of 20 points (since he was scored on the 1st and 3rd assignments but excluded from the 2nd assignment), which is 100% for the subcourse.  

However, in the master course, his subcourse grade will be fetched as being out of only 20 points (instead of 30 points for everyone else), since he was excluded from the 2nd assignment.  That way, if subcourses have different point values (say a subcourse is for exams vs. practice quizzes), the final grade aggregated in the master course will accurately reflect the different weightings of the subcourses based on their actual point values.  Fetching the percentage into the final master course would not reflect the different point values an instructor has assigned to various quizzes and assignments within a subcourse.

Hope that makes sense and brings clarity instead of further confusion--grading can get messy, but Moodle and your subcourse plugin actually opens up a realm of possibilities and could potentially help bring clarity to assessment for both students and teachers (e.g. I like to use your subcourse plugin to separate each topic in physics into a subcourse--now instead of all my students assignments being lumped into large categories, they can see how they are progressing and doing in each unit to work towards mastery and success)!

**Comment by mudrd8mz** [comment] 2020-07-11 17:44
This is how grades would be imported with the default "Real values" option (existing behaviour):

![image](https://user-images.githubusercontent.com/85831/87230201-933a0380-c3ae-11ea-84ea-80a78bc02d35.png)

When the "Percentual values" is selected as the mode of fetching grades, the same grades are imported as:

![image](https://user-images.githubusercontent.com/85831/87230225-cbd9dd00-c3ae-11ea-8d98-2a1e63fe5c9e.png)

You can see that in the first case, the real (points) value matches the referenced course and in the later case, the real value has been recalculated so that the percentage matches in both places.

**Comment by jjliaw** [comment] 2020-07-11 17:53
Hi David:

Ahh--the screenshots are very helpful!

Using Batur as an example, is there a way to import his grade to the meta course so that BOTH his points (20 / 20) AND percentage (100%) transfer to the meta course, BUT his meta course total reflects the fact that he had an excluded assignment of 10 points so that his meta course total is only calculated out of 20 points instead of 30 points for everyone else?

I believe this is the expected behavior most teachers would want--in other words, if I had to excuse a student from an assignment, then the assignment should not count for or against the student and would be completely excluded from their grade calculation.

During the COVID-19 quarantine and sudden shift to remote learning for everyone, I had some students in extenuating circumstances and had to exclude them from assignments (e.g. family had to suddenly move to an apartment, family member got sick, some had to help care for younger siblings, get a part-time job to help with family expenses, etc.)--so I was hoping for a way to use the Exclude grade feature in Moodle with your fantastic subcourse plugin to accurately calculate the final meta course grade to reflect their excluded assignments.

Thanks David!

**Comment by mudrd8mz** [comment] 2020-07-12 08:06
> is there a way to import his grade to the meta course so that BOTH his points (20 / 20) AND percentage (100%) transfer to the meta course

No, there isn't. As I tried to explain above - the grade item associated with the Subcourse activity module (i.e. the column in the main course gradebook) can have one and only one value set as the maximum grade and that is 30 in this case (copied over from the referenced course). There is no way in Moodle to have different max grade for each student. That is why the teachers need to choose whether it is the real value or percentage that they want to have synced. The other one cannot be guaranteed if there are excluded grades in the referenced course.

There is no way i am aware of to do this - neither manually nor automatically via the plugin. If you are aware of a gradebook setup that would allow you to achieve this, please share.

**Comment by mudrd8mz** [comment] 2020-07-13 19:41
Implemented in c7e434f

**Closed by mudrd8mz** 2020-07-13 19:41 UTC
Labels: MUST HAVE

**Comment by jjliaw** [comment] 2020-07-13 20:23
Hi David:

I see your dilemma as the programmer and appreciate your patience in trying to troubleshoot this!

The only thing I can think of is to see if there is a way to implement the Subcourse grade to use the same code that the Moodle gradebook uses when calculating Excluded grades--somehow the Moodle gradebook will take the total points earned divided by the total points possible for an individual student (which is the course total points possible MINUS points total from excluded assigments) to populate the final course grade for a student....

....so if there is a possibility of having the subcourse module grab not the total course grade, but the total points earned by a student and the total points possible for an __individual__ student, then I think we could make this work.

Hope this is helpful, but I understand if this is too difficult to implement--again, thank you for your patience and hard work in trying to implement new features as well as troubleshoot the pesky excluded grades problem!!!

**Comment by mudrd8mz** [comment] 2020-07-13 23:08
> but I understand if this is too difficult to implement

No, this is not about being difficult. This is about being impossible, given the way how the Moodle Gradebook has been designed and how it works.

As I was trying to illustrate via the screenshots above. The student Adelina receives 20 points in the referenced course and the "Natural" aggregation method calculates it as 20 out of 20 and shows it as 100% if it was configured to exclude empty grades. The student Nicolai also receives 20 points, but he gets only 67% because in his case, it is 20 out of 30.

If you want to fetch these grades into a standalone grade item (column) in another course, this column itself must have some max value. There is no way in Moodle to show 20 points as both 67% and 100% anywhere else but in aggregated columns.

That is why the only available fix to approach this was to introduce the setting and let the teachers decide whether it is the points or the percentages that they want to have matched. 

> and the total points possible for an individual student

No, that is not possible. Every grade item in the gradebook has its max value which is shared for all users.

Put in another words: You cannot have an Assignment or a Quiz that would be out of 20 points for some students, and out of 30 points for other students. That applies to all activity modules and manually created grade items, including the Subcourse activitity too.

**Comment by jjliaw** [comment] 2020-07-13 23:19
Hi David:

Thanks for the detailed explanation and your extraordinary patience--now I understand better how the Moodle gradebook can not implement a Subcourse from having a grade Excluded since every student would need to have the same point value assigned to the assignment total!!!  Funny how something that should be simple is in fact very complicated!!!

However, if a teacher used percentages, then Subcourse would calculate excluded grades "correctly" since the subcourse would already have the excluded grades accounted for when Moodle aggregates the final subcourse grade, correct?

That could be a work around, though grading by percentages is very different then grading by total points via the "Natural" aggregation method.

Thanks again David for your fantastic plugin--I suspect more teachers will find Subcourse extremely useful as we build more complex and rich classes for our students, especially during COVID-19!

Regards,

--Joe
