### ISSUE TITLE
'Course completion' criteria not showing for 'Student must complete the referenced course'

### ISSUE THREAD

**Issue by ChrisCYC** [mudrd8mz/moodle-mod_subcourse#92] opened 2024-08-01 10:53 UTC
Moodle v. 4.1 - Plugin version 2023103003

Hi, When completion tracking is set to just '**Student must complete the referenced course to complete this activity.**' on a subcourse activity, no completion criteria is visible on the moodle course page. This doesn't change when they have completed the subcourse. 

Subcourse is still working, as we can see they have completed the subcourse activity in the actvity completion reports screen, but the student cannot see that this has been completed.  

Screenshot 1: Settings for subcourse activity module

![Image 1](https://github.com/user-attachments/assets/b96ae252-a4cd-4a68-aef0-25f7e25132b6)

Screenshot 2: View of Moodle page where completion criteria isn't shown. The arrows display where completion should be shown. 

![Image 2](https://github.com/user-attachments/assets/f977a0c1-5491-41cf-9ef8-11422193f11a)

 Any thoughts or guidance would be much appreciated. 

Thanks 

Chris

**Comment by danmarsden** [comment] 2024-08-02 03:28
Hi there - this looks to be a duplicate of #86  and #90 - unfortunately it's a known issue but not something I have time to work on as a volunteer right now. If you have internal development capabilities, pull requests are always welcome, otherwise feel free to reach out privately if you would like to fund improvements on the subcourse plugin!

**Closed as completed by danmarsden** 2024-08-02 03:28 UTC

**Comment by ChrisCYC** [comment] 2024-08-02 07:50
Thanks for the quick reply Dan, I'm going to see if our Moodle host are able to revert back to the 10.1.0 (2021021401) version for now. Funds are sort in FE :-( We haven't upgraded our Moodle platform since we updated the plugin and it was working fine beforehand, so this seems like the sensible course of action for now.
